### ISSUE TITLE
Readme says use "flask run" to start the app and create users. Is it needed?

### ISSUE THREAD

**Issue by TheGardenMan** [app-generator/django-volt-dashboard#10]

**Comment by app-generator** [comment]
Hello @TheGardenMan 

`flask run` is needed to start the app.
Once is up & running, you can access the private pages that are available for authenticated users.   

In other words, `flask run` is not creating any users. just starts the project.

**Comment by TheGardenMan** [comment]
Hi thanks for the reply!

I can't see flask in `requirements.txt`
Is that expected?
I have just started going through the code so I haven't understood the working yet

**Comment by app-generator** [comment]
Hello @TheGardenMan 

Please ignore my latest sentence. To start the app run `python manage.py runserver`. 

Flask mention is visible because the README is generated with this `bug`. 
Now I'm updating the generator to remove `Flask` mentions for Django-based kits. 

Thank you for your vigilance :)
