### ISSUE TITLE
Could not parse the remainder

### ISSUE THREAD

**Issue by agerson** [app-generator/django-volt-dashboard#14]
http://127.0.0.1:8000/register/ produces this error

<img width="1321" alt="CleanShot 2022-11-05 at 21 39 26@2x" src="https://user-images.githubusercontent.com/334672/200150068-f3dfa37c-959d-4b71-8efa-33b373ebc04f.png">

**Comment by app-generator** [comment]
Hello @agerson 

Thank you for the report. The [App Generator](https://appseed.us/generator/volt-dashboard/) will be fixed soon.

**Comment by app-generator** [comment]
Hello @agerson 

Please regenerate the product:
