### ISSUE TITLE
Customize or remove unneeded dashboard cards?

### ISSUE THREAD

**Issue by sridhar562345** [app-generator/django-volt-dashboard#2]
![image](https://user-images.githubusercontent.com/59284206/142842409-254c2f8c-1d4f-43fa-87d5-38ac5b20d62e.png)

How to remove unwanted dashboard information cards?

**Comment by app-generator** [comment]
Hello @sridhar562345, 

Try to edit the dashboard page. The link for the main dashboard is thin one `apps/templates/home/index.html`

https://github.com/app-generator/django-volt-dashboard/blob/master/apps/templates/home/index.html

**Comment by sridhar562345** [comment]
Hello @app-generator ,

I am installing it as a custom admin theme using:
```shell
pip install django-admin-volt
```
so where should I place my customized HTML file inside my Django app?

**Comment by dlopespenna** [comment]
> Hello @app-generator ,
> 
> I am installing it as a custom admin theme using:
> 
> ```shell
> pip install django-admin-volt
> ```
> 
> So where should I place my customized HTML file inside my Django app to override default templates?

@sridhar562345 were you able to replace the default HTML file?
I'm trying to do the same thing.

**Comment by sridhar562345** [comment]
> > Hello @app-generator ,
> > I am installing it as a custom admin theme using:
> > ```shell
> > pip install django-admin-volt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So where should I place my customized HTML file inside my Django app to override default templates?
> 
> @sridhar562345 were you able to replace the default HTML file? I'm trying to do the same thing.

Hi @dlopespenna,

You will have to fork the repo and change the template according to your use case, that's the only way I got succeded. 
I wasn't able to do this by replacing the templates directly in the Django templates.

**Comment by andreashhpetersen** [comment]
> > Hello @app-generator ,
> > I am installing it as a custom admin theme using:
> > ```shell
> > pip install django-admin-volt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So where should I place my customized HTML file inside my Django app to override default templates?
> 
> @sridhar562345 were you able to replace the default HTML file? I'm trying to do the same thing.

Hi @dlopespenna and @sridhar562345 
You can override or replace by adding your own file to a directory called `admin` somewhere on your template search path (defined in `settings.TEMPLATES`). For example, in my settings I have
```python
TEMPLATES = [
    {
        'BACKEND': ...,
        'DIRS': [ BASE_DIR \ 'templates' ],
    },
]
```
and then I can override the dashboard default by adding my own `templates/admin/index.html`.

The documentation doesn't provide much info on working with `django-admin-volt`, but you can generally just follow the normal Django documentation [on the admin page](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#overriding-admin-templates).

**Comment by andreashhpetersen** [comment]
> > Hello @app-generator ,
> > I am installing it as a custom admin theme using:
> > ```shell
> > pip install django-admin-volt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So where should I place my customized HTML file inside my Django app to override default templates?
> 
> @sridhar562345 were you able to replace the default HTML file? I'm trying to do the same thing.

Hi @dlopespenna and @sridhar562345 
You can override or replace by adding your own file to a directory called `admin` somewhere on your template search path (defined in `settings.TEMPLATES`). For example, in my settings I have
```python
TEMPLATES = [
    {
        'BACKEND': ...,
        'DIRS': [ BASE_DIR \ 'templates' ],
    },
]
```
and then I can override the dashboard default by adding my own `templates/admin/index.html`.

The documentation doesn't provide much info on working with `django-admin-volt`, but you can generally just follow the normal Django documentation [on the admin page](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#overriding-admin-templates).

**Comment by Spirit-Maker** [comment]
> > > Hello @app-generator ,
> > > I am installing it as a custom admin theme using:
> > > ```shell
> > > pip install django-admin-volt
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So where should I place my customized HTML file inside my Django app to override default templates?
> > 
> > 
> > @sridhar562345 were you able to replace the default HTML file? I'm trying to do the same thing.
> 
> Hi @dlopespenna,
> 
> You will have to fork the repo and change the template according to your use case, that's the only way I got succeded. I wasn't able to do this by replacing the templates directly in the Django templates.

I have copied templates and templatetags from the admin-volt in library to my app. I am facing issue related to templatetags. Apparently you have to add app in settings which is already in installed apps becuase it is my main app. I even renamed the templatetags py file to app name. Screenshot attached for reference.

![image](https://github.com/app-generator/django-volt-dashboard/assets/39567452/8987171b-ff80-4412-a8a7-b4d1f31cee1d)

![image](https://github.com/app-generator/django-volt-dashboard/assets/39567452/c4e4949a-5444-40fa-ada7-0874441ade13)

Please guide me what I am doing wrong in this case.

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
