### ISSUE TITLE
how to change the date format of the datepicker component

### ISSUE THREAD

**Issue by chronos-dev** [app-generator/django-volt-dashboard#4]
how to change the date format of the datepicker component to "pt-br"?

![image](https://user-images.githubusercontent.com/48959920/154165905-f6347845-deca-4f8f-9aff-3aa0ecc331dc.png)

**Comment by app-generator** [comment]
Hello @chronos-dev 

Volt uses the date picker plugin fully documented here: 

https://mymth.github.io/vanillajs-datepicker/#/

Regarding your specific localization, probably a new file with your specific language settings should be created:

https://mymth.github.io/vanillajs-datepicker/#/i18n

Let us know your progress.

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
